version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'password'
      PIHOLE_DNS_: '10.1.2.6'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'    
    networks:
      dns:
        ipv4_address: '10.1.2.5'
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    environment:
      TZ: 'America/New_York'
    networks:
      dns:
        ipv4_address: '10.1.2.6'
    restart: unless-stopped

networks:
  dns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.2.0/24
          gateway: 10.1.2.1
